name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-24.04, windows-2022]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Enable long paths in git
        if: matrix.os == 'windows-2022'
        run: |
          git config --system core.longpaths true

      - name: Enable long paths in windows
        if: matrix.os == 'windows-2022'
        run: |
          New-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem" `
            -Name "LongPathsEnabled" -Value 1 -PropertyType DWORD -Force

      - name: Checkout self
        uses: actions/checkout@v4

      - name: Checkout zed
        uses: actions/checkout@v4
        with:
          repository: zed-industries/zed
          ref: refs/tags/v0.211.6
          path: zed

      - name: Copy config file
        run: |
          cp .cargo/config.toml zed/.cargo/

      - name: Install linux dependencies
        if: matrix.os == 'ubuntu-24.04'
        run: |
          sudo apt update
          sudo apt install -y libx11-dev libasound2-dev libx11-xcb-dev libxkbcommon-dev libxkbcommon-x11-dev

      - name: Install rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          target: wasm32-wasip1

      - name: Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.os }}-${{ hashFiles('Cargo.lock') }}
          workspaces: "zed -> target"

      - name: Create release dir
        shell: bash
        run: |
          if [ "${{ matrix.os }}" == "ubuntu-24.04" ]; then
            mkdir -p release/linux/zed/bin release/linux/zed/libexec
          fi

          if [ "${{ matrix.os }}" == "windows-2022" ]; then
            mkdir -p release/windows/zed/bin
          fi

      - name: Setup MSVC
        if: matrix.os == 'windows-2022'
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64
          sdk: 10.0.20348

      - name: Build cli
        shell: bash
        run: |
          cd zed/crates/cli
          cargo b -r
          cd -

          if [ "${{ matrix.os }}" == "ubuntu-24.04" ]; then
            mv zed/target/release/cli release/linux/zed/bin/zed
          fi

          if [ "${{ matrix.os }}" == "windows-2022" ]; then
            mv zed/target/release/cli.exe release/windows/zed/bin/zed.exe
          fi

      - name: Build editor
        shell: bash
        run: |
          cd zed
          cargo b -r
          cd -

          if [ "${{ matrix.os }}" == "ubuntu-24.04" ]; then
            mv zed/target/release/zed release/linux/zed/libexec
          fi

          if [ "${{ matrix.os }}" == "windows-2022" ]; then
            mv zed/target/release/zed.exe release/windows/zed
          fi

      - name: Linux archive
        if: matrix.os == 'ubuntu-24.04'
        uses: actions/upload-artifact@v4
        with:
          name: zed_${{ matrix.os }}
          path: |
            release/linux/zed

      - name: Windows archive
        if: matrix.os == 'windows-2022'
        uses: actions/upload-artifact@v4
        with:
          name: zed_${{ matrix.os }}
          path: |
            release/windows/zed
