name: LinuxBuild 

on:
  push

jobs:
  build:
    runs-on: ubuntu-2024
    strategy:
      matrix:
        backend: [vulkan]
        include:
          - backend: vulkan
            artifact_name: zed-release
            rustflags: ""
      fail-fast: false

    steps:
      - name: Checkout self
        uses: actions/checkout@v4

      - name: Checkout Zed
        uses: actions/checkout@v4
        with:
          repository: zed-industries/zed
          ref: refs/tags/v0.199.10
          path: zed

      - name: Install rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          override: true
          target: wasm32-wasip1

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.backend }}-${{ hashFiles('Cargo.lock') }}
          workspaces: "zed -> target"

      - name: Setup rustflags
        run: ./scripts/parse-rustflags.sh ${{ matrix.rustflags }}

      - name: Build release
        working-directory: zed
        run: cargo b -r

      - name: Archive build
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: zed/target/release/zed
